# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e0859d02faa7a001e84f8244b03e170cd0151a14277e56c4918627b7426550a26389c8c5e5a95adfaa23ece9d69a412cb8143ac37874a762bd03da0378a014d5

test:
  secret_key_base: 77ac3c7cd9683e1385d9a40dfc8c75e7ad4457948e805dd8267b90fd2a1a909868831672f41606d4a279cb902c5a8cedaf9de4b993ea331236aca0105807345e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
